### ISSUE TITLE
[ Solved ] How to use

### ISSUE THREAD

**Issue by JibrilYasin** [ThinkMe/pagination#1]
Hi @ThinkMe 

I tried to implement it on my project, but I find:

"Call to a member function route() on null"

This is my routes :
Route::get('/{page?}', array('as'=>'list.page','uses'=>'WelcomeController@index'));

This is my controller :

<?php
namespace App\Http\Controllers;
use App\Mylib\Tanggal;
use App\Mylib\Kode;
use App\Pagination;
use App\Albumphoto;
use App\Paginator;

class WelcomeController extends Controller {

```
public function __construct()
{
    $this->middleware('guest');
}

public function index()
{
    $list = new Paginator();
    $item=Albumphoto::get_data();
    $page=1;
    $list = $list->make($item, count($item), 1, $page, ['path' => Paginator::resolveCurrentPath(),]);
    $list->route('list.page');
    $list->pagesProximity(3);

    Paginator::presenter(function() use ($list) {
        return new MyPresenter($list);
    });
    //$list->route('/');
    //$list->pagesProximity(3);
    //$data['viewdata']=Albumphoto::get_data_paginate();
    //return view('tes',$data);

}
```

}

Please help:D, I am very Newbie

**Comment by ThinkMe** [comment]
Maybe
Wrong new Pagination

**Comment by JibrilYasin** [comment]
So, how do I fix it?

This is my Model :

public static function get_data_paginate(){
        $query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
                                            ->leftJoin('users','albumphoto.userid','=','users.id')
                                            ->orderBy('albumphoto.updated_at','asc')
                                            ->paginate(1);
        return $query;
    }

**Comment by ThinkMe** [comment]
before paginate(1)

**Comment by JibrilYasin** [comment]
Sorry, I don't understand, what do you mean?

**Comment by ThinkMe** [comment]
public static function get_data_paginate(){
$query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
->leftJoin('users','albumphoto.userid','=','users.id')
->orderBy('albumphoto.updated_at','asc')
return $query;
}

**Comment by ThinkMe** [comment]
public static function get_data_paginate(){
$query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
->leftJoin('users','albumphoto.userid','=','users.id')
->orderBy('albumphoto.updated_at','asc');
return $query;
}

**Comment by JibrilYasin** [comment]
Still error,
I use this model:

public static function get_data_paginate(){
        $query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
                                            ->leftJoin('users','albumphoto.userid','=','users.id')
                                            ->orderBy('albumphoto.updated_at','asc');
        return $query;
    }

**Comment by ThinkMe** [comment]
what error info

**Comment by JibrilYasin** [comment]
I get the same error:
"Call to a member function route() on null"

**Comment by ThinkMe** [comment]
$list = new Paginator();
$list->pagesProximity(5)->paginate($query, 15);

**Comment by JibrilYasin** [comment]
$list = new Paginator();
$item=Albumphoto::get_data_paginate();
$data=$list->pagesProximity(5)->paginate($item, 1);

I tried var_dump ($data), but the result is "Null". In the table filled in 3 records.

Sorry to have been disturb you. :D

**Comment by ThinkMe** [comment]
$query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
->leftJoin('users','albumphoto.userid','=','users.id')
->orderBy('albumphoto.updated_at','asc')

$list = new Paginator();
$list->pagesProximity(5)->paginate($query, 15);

**Comment by JibrilYasin** [comment]
The result still "Null",, :D

**Comment by ThinkMe** [comment]
dump($query);

**Comment by JibrilYasin** [comment]
I get result :

Builder {#197 ▼
  #query: Builder {#196 ▼
    #connection: MySqlConnection {#182 ▼
      #pdo: PDO {#180 ▶}
      #readPdo: null
      #reconnector: Closure {#195 ▶}
      #queryGrammar: MySqlGrammar {#193 ▶}
      #schemaGrammar: null
      #postProcessor: MySqlProcessor {#194}
      #events: Dispatcher {#5 ▶}
      #fetchMode: 8
      #transactions: 0
      #queryLog: []
      #loggingQueries: false
      #pretending: false
      #database: "fili"
      #tablePrefix: ""
      #config: array:10 [▶]
    }
    #grammar: MySqlGrammar {#193 ▼
      #selectComponents: array:11 [▶]
      #tablePrefix: ""
    }
    #processor: MySqlProcessor {#194}
    #bindings: array:5 [▼
      "select" => []
      "join" => []
      "where" => []
      "having" => []
      "order" => []
    ]
    +aggregate: null
    +columns: array:6 [▼
      0 => "albumphotoid"
      1 => "albumphotoname"
      2 => "albumphotolink"
      3 => "albumphoto.created_at"
      4 => "albumphoto.updated_at"
      5 => "users.name"
    ]
    +distinct: false
    +from: "albumphoto"
    +joins: array:1 [▼
      0 => JoinClause {#198 ▶}
    ]
    +wheres: null
    +groups: null
    +havings: null
    +orders: array:1 [▼
      0 => array:2 [▼
        "column" => "albumphoto.updated_at"
        "direction" => "asc"
      ]
    ]
    +limit: 15
    +offset: 0
    +unions: null
    +unionLimit: null
    +unionOffset: null
    +unionOrders: null
    +lock: null
    #backups: []
    #operators: array:26 [▼
      0 => "="
      1 => "<"
      2 => ">"
      3 => "<="
      4 => ">="
      5 => "<>"
      6 => "!="
      7 => "like"
      8 => "like binary"
      9 => "not like"
      10 => "between"
      11 => "ilike"
      12 => "&"
      13 => "|"
      14 => "^"
      15 => "<<"
      16 => ">>"
      17 => "rlike"
      18 => "regexp"
      19 => "not regexp"
      20 => "~"
      21 => "~_"
      22 => "!~"
      23 => "!~_"
      24 => "similar to"
      25 => "not similar to"
    ]
    #useWritePdo: false
  }
  #model: Albumphoto {#183 ▼
    #table: "albumphoto"
    #connection: null
    #primaryKey: "id"
    #perPage: 15
    +incrementing: true
    +timestamps: true
    #attributes: []
    #original: []
    #relations: []
    #hidden: []
    #visible: []
    #appends: []
    #fillable: []
    #guarded: array:1 [▼
      0 => "*"
    ]
    #dates: []
    #casts: []
    #touches: []
    #observables: []
    #with: []
    #morphClass: null
    +exists: false
  }
  #eagerLoad: []
  #macros: []
  #onDelete: null
  #passthru: array:12 [▼
    0 => "toSql"
    1 => "lists"
    2 => "insert"
    3 => "insertGetId"
    4 => "pluck"
    5 => "count"
    6 => "min"
    7 => "max"
    8 => "avg"
    9 => "sum"
    10 => "exists"
    11 => "getBindings"
  ]
}

**Comment by ThinkMe** [comment]
dd($query->toSql())

**Comment by JibrilYasin** [comment]
I get the results

"select `albumphotoid`, `albumphotoname`, `albumphotolink`, `albumphoto`.`created_at`, `albumphoto`.`updated_at`, `users`.`name` from `albumphoto` left join `users` on `albumphoto`.`userid` = `users`.`id` order by `albumphoto`.`updated_at` asc limit 15 offset 0"

**Comment by ThinkMe** [comment]
can you sql exec ?

**Comment by ThinkMe** [comment]
$query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
->leftJoin('users','albumphoto.userid','=','users.id')
->orderBy('albumphoto.updated_at','asc')
$paginator = new Paginator();
$paginator->pagesProximity(5)->paginate($query, 15);

I have no problem here

my code:
$query = User::with('relation')->select()->orderBy('id', 'desc');
$paginator = new Paginator();
$paginator->pagesProximity(5)->paginate($query, 15);
$data['listData'] = $paginator;
$view = view('index.index', $data);
return $view;

**Comment by JibrilYasin** [comment]
Is there anything wrong with my Controller?

<?php
namespace App\Http\Controllers;
use App\Albumphoto;
use App\Paginator;

class WelcomeController extends Controller {
}

I replace "namespace ThinkMe\Pagination" to "namespace App" in Paginator.php

And I copy the file Paginator.php into the folder "app"

**Comment by ThinkMe** [comment]
Do not see the problem, only to this part of your code package sent to my e-mail in the

**Comment by JibrilYasin** [comment]
This is my controller

<?php
namespace App\Http\Controllers;

use App\Albumphoto;
use App\Paginator;

class WelcomeController extends Controller {

```
public function __construct()
{
    $this->middleware('guest');
}

public function index()
{
    $list = new Paginator();
    //$list = new Paginator();
    //$item=Albumphoto::get_data_paginate();
    //$data=$list->route('/')->pagesProximity(5)->paginate($item, 1);

    $query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
```

->leftJoin('users','albumphoto.userid','=','users.id')
->orderBy('albumphoto.updated_at','asc');

$data=$list->pagesProximity(5)->paginate($query, 15);

```
    //$list->route('/');
    //$list->pagesProximity(3);
    //$data['viewdata']=Albumphoto::get_data_paginate();
    return json_encode($data);

}
```

}

**Comment by ThinkMe** [comment]
my code no problem
$query = User::with('relation')->select()->leftJoin('company', 'company.id', '=', 'user.company_id')->orderBy('user.id', 'desc');
$paginator = new Paginator();
$paginator->pagesProximity(5)->paginate($query, 15);
$data['listData'] = $paginator;
dump($data['listData']->toArray());

**Comment by ThinkMe** [comment]
Show me the only project(zip) send to my email.
I look at where find the problem is

**Comment by JibrilYasin** [comment]
Oh ok,, What is your email?

**Comment by ThinkMe** [comment]
this my email
i@yea.im

**Comment by JibrilYasin** [comment]
I can't upload a zip in gmail, so I uploaded in https://www.4shared.com/zip/0cuSuklkce/v4_online.html

Thank you so much for your help

**Comment by ThinkMe** [comment]
I can't down.
many ad

**Comment by ThinkMe** [comment]
can you  use mail.qq.com ?

**Comment by ThinkMe** [comment]
down success

**Comment by JibrilYasin** [comment]
Ok thanks master :D

**Comment by ThinkMe** [comment]
```
$query=Albumphoto::select('albumphotoid','albumphotoname','albumphotolink','albumphoto.created_at','albumphoto.updated_at','users.name')
        ->leftJoin('users','albumphoto.userid','=','users.id')
        ->orderBy('albumphoto.updated_at','asc');

        $list = new Paginator();
        $list->pagesProximity(5)->paginate($query, 15);
        $data['list']=$list;
        return view('welcome', $data);

```

<div class="content">
                <div class="title">Laravel 5</div>

```
            <div class="quote">{{ Inspiring::quote() }}</div>
            @foreach($list as $data)
                {{$data->albumphotoname}}
            @endforeach
        </div>
```

**Comment by ThinkMe** [comment]
dd($list->toArray());

**Comment by JibrilYasin** [comment]
Yeaaahhh,, it works, I am very happy, thank you very much master

$list = new Paginator();
$list->route('list.page')->pagesProximity(5)->paginate($query, 1);
$data['list']=$list;
