### ISSUE TITLE
Error in Laravel 5.4

### ISSUE THREAD

**Issue by JibrilYasin** [ThinkMe/pagination#2]
Hi @ThinkMe ,, sorry,, Can you help me? I get an error on laravel 5.4.

ErrorException 
Declaration of App\Paginator::links() should be compatible with Illuminate\Pagination\LengthAwarePaginator::links($view = NULL, $data = Array)

This is my Controller 
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use App\Http\Requests;
use App\Services\Date;
use App\Services\Code;
use JavaScript;
use Session;
use Image;
use File;
use App\User;
use Auth;
use Mail;
use Hash;
use DateTime;
use App\Paginator;

class UserController extends Controller
{

    public function users(Request $request){

            $query=User::get_data();
            $list = new Paginator();
            $list->route('myusers')->pagesProximity(5)->paginate($query, 5);

            $data['users']=$list;
            $data['pagination']=$list->render();

   }

}

Thanks for attention..

**Comment by ThinkMe** [comment]
The version I use is also laravel 5.4.
Look at the namespace
use ThinkMe\Pagination\Paginator;

in views  
index.blade.php
common/paginate.blade.php

{!!$list->render('common.paginate')!!}
or
{!!$list->links('common.paginate')!!}

Where is your paging template?

**Comment by JibrilYasin** [comment]
Hi,, this is my view

<ul>
    @foreach($users as $view)
        <li>{{ $view['name'] }}</li>
    @endforeach
</ul>
 {!! $pagination !!}

**Comment by ThinkMe** [comment]
a paging template
paginate.blade.php

**Comment by JibrilYasin** [comment]
paginate.blade.php

@if ($paginator->lastPage() > 1)
    <div class="pagination">
        @if($paginator->currentPage()>1)
            <a href="{{$paginator->url($paginator->currentPage()-1)}}" class="first"></a>
        @else
            <a href="javascript:;" class="first-none"></a>
        @endif
            @foreach ($paginator->getPagesRange() as $page)
                @if($paginator->currentPage()==$page)
                    <span class="current">{{$page}}</span>
                @else
                    <a href="{{$paginator->url($page)}}">{{$page}}</a>
                @endif
            @endforeach
            @if($paginator->currentPage()<$paginator->lastPage())
                <a href="{{$paginator->url($paginator->currentPage()+1)}}" class="last last-none"></a>
            @else
                <a href="javascript:;" class="last-none"></a>
            @endif
    </div>
@endif

**Comment by ThinkMe** [comment]
$list->render('paginate')
or
$list->links('paginate')

**Comment by JibrilYasin** [comment]
i use,, $list->links('paginate'),,

Yeahh now work, but in the url there is no parameter like "/2 or/3",, Just http://localhost/laravel/5.4/back-users?page=2

**Comment by ThinkMe** [comment]
use ThinkMe\Pagination\Paginator;
        $list = new Paginator();
        $query = Order::select();
        $list->route('list.page')->pagesProximity(3)->paginate($query, 10);
        dd($list->appends(request()->all())->links('paginate'));

      route.php
      Route::get('user/{page}', ['as' => 'list.page', 'uses' => 'IndexController@index']);

**Comment by JibrilYasin** [comment]
The result 

HtmlString {#65 ▼
  #html: ""
}

**Comment by JibrilYasin** [comment]
yeaah,, solved,,  I forgot to add the parameters on the route. thanks @ThinkMe

**Comment by JibrilYasin** [comment]
Route::get('/back-users/{page?}'
